theme: jekyll-theme-cayman
title: "-- Frontiers in Gravity and Fundamental Physics --  (YU Workshop 2022)"
avatar: "YU_symbolmark.png"
title-img: "YU_symbolmark.png"
description: 26th November, 2022 to 27th November, 2022, Yonezawa, Yamagata
github:
  is_project_page: false
