theme: jekyll-theme-cayman
title: "-- Frontiers in Gravity and Fundamental Physics --  (YU Workshop 2025)"
avatar: "YU_symbolmark.png"
title-img: "YU_symbolmark.png"
description: 3rd March, 2025 to 4th March, 2025, Yonezawa, Yamagata
github:
  is_project_page: false
